version: '3'

services:
  mail:
    image: rkusuma/postfix-sasl-dkim
    environment:
      - MTA_DOMAIN=example.com
      - MTA_HOST=mail.example.com
      - MTA_USERS=test_user:test_password
      - MTA_MYNETWORKS=127.0.0.0/8,[::1]/128,[::ffff:127.0.0.0]/104,139.162.100.207/32
      - DEBUG=true
    ports:
      - "${MAIL_PORT:-25}:25"
