version: '3'

services:
  mail:
    image: hillliu/postfix-sasl-dkim
    environment:
      - MTA_DOMAIN=${MTA_DOMAIN}
      - MTA_HOST=${MTA_HOST}
      - MTA_USER=${MTA_USER}
      - MTA_PASSWORD=${MTA_PASSWORD}
      - DEBUG=${DEBUG}
    volumes:    
      - "${DKIM_DATA:-./data/dkim}:/etc/opendkim/keys" 
      - "${TLS_DATA:-./data/tls}:/etc/postfix/tls" 
      - "${POSTFIX_DATA:-./data/postfix}:/var/spool/postfix"
    ports:
      - "${MAIL_PORT:-25}:25"
